package frontEnd;

public interface Texto {
	
	
	//Menu

	public static final String TEXTO_MENU ="Que te gustaria hacer?\n"

	+ "1. Ver catalogo\n"

	+ "2. Ver catalogo de un solo genero\n"

	+ "3. Insertar contenido\n"

	+ "4. Actualizar Valoracion del contenido\n"

	+ "5. Borra contenido\n"

	+ "6. Salir";
	
	//Main
	public static final String TEXTO_TITULO_CONTENIDO2 = "Dime el titulo del contenido del que quieres cambiar la valoracion";
	public static final String TEXTO_VALORACION_NUEVA = "¿Que valoracion quieres meter?";
	public static final String TEXTO_TITULO_CONTENIDO = "Digame el titulo";
	public static final String TEXTO_GENERO_CONTENIDO = "Digame a que genero pertenece\n1. Accion\n2. Aventura\n3. Comedia\n4. Drama\n5. Musical\n6. Terror\n7. Thriller";
	public static final String TEXTO_GENERO_SELECT_CONTENIDO = "Digame que genero quiere buscar\n1. Accion\n2. Aventura\n3. Comedia\n4. Drama\n5. Musical\n6. Terror\n7. Thriller";

	public static final String TEXTO_VALORACION_CONTENIDO = "Dame tu valoracion";
	public static final String TEXTO_FECHA_ESTRENO = "Dime el año de estreno";
	public static final String TEXTO_NOMBRE_DIRECTOR = "Dime el nombre de su director";
	public static final String TEXTO_NUMERO_ACTORES = "¿Cuantos actores quieres introducir?";
	public static final String TEXTO_NOMBRE_ACTOR = "Dime el nombre de los protagonistas";
	public static final String TEXTO_DURACION_PELICULA = "Dime cuanto dura esta pelicula:";
	public static final String TEXTO_HORAS_PELICULA = "Horas de la pelicula:";
	public static final String TEXTO_MINUTOS_PELICULA = "Minutos de la pelicula:";
	public static final String TEXTO_TEMPORADAS_SERIE = "Cuantas temporadas tiene?";
	public static final String TEXTO_NUMERO_CAPITULOS_TEMPORADA = "Dime el numero de capitulos que tiene esta temporada";
	public static final String TEXTO_TITULO_CAPITULO = "Dime el titulo del capitulo";
	public static final String TEXTO_DURACION_CAPITULO = "Dime la duracion del capitulo(En minutos)";
	public static final String TEXTO_FECHA_ESTRENO_TEMPORADA = "Cuando se estreno esta temporada?";
	public static final String TEXTO_ANYO_ESTRENO = "Dime el año de estreno";
	public static final String TEXTO_MES_ESTRENO = "Dime el mes de estreno";
	public static final String TEXTO_DIA_ESTRENO = "Dime el dia de estreno";
	public static final String TEXTO_OPCIONES_CONTENIDO = "¿Que quieres añadir?\n1. Una pelicula\n2. Una serie";
	public static final String TEXTO_OPCION_NO_VALIDA = "Por favor, introduzca un valor valido";
	public static final String TEXTO_TITULO_BORRAR_CONTENIDO = "Dime el titulo del contenido que quieres borrar";
	public static final String TEXTO_ERROR_NUMERO= "Error: INTRODUZCA UN NÚMERO VALIDO";
	public static final String TEXTO_ERROR_DELETE_NO_ENCONTRADO="No se ha encontrado el contenido";

	//Base de datos conexiones
	public static final String USUARIO="System";
	public static final String CONTRASENA="Admin2023";
	public static final String ENLACE_BD = "jdbc:oracle:thin:@localhost:1521:XE";



	//Base de datos tabla
	public static final String CREAR_TABLA="CREATE TABLE ContenidoAudiovisual ("

			+ "IDAudiovisual NUMBER GENERATED BY DEFAULT AS IDENTITY,"

			+ "Titulo VARCHAR(150),"

			+ "Genero VARCHAR(20),"

			+ "ValoracionMedia DECIMAL(4,2),"

			+ "Fecha DATE,"

			+ "Duracion NUMBER,"

			+ "Director VARCHAR(100),"

			+ "Actores VARCHAR(150),"

			+ "NumeroDeTemporadas INTEGER,"

			+ "CapitulosTotales INTEGER,"

			+"PRIMARY KEY(IDAudiovisual)"

			+ ")";
	
//	CREATE TABLE ContenidoAudiovisual (
//			IDAudiovisual NUMBER GENERATED BY DEFAULT AS IDENTITY,
//			Titulo VARCHAR(20),
//			Genero VARCHAR(20),
//			ValoracionMedia DECIMAL(4,2),
//			Fecha DATE,
//			Duracion NUMBER,
//			Director VARCHAR(100),
//			Actores VARCHAR(150),
//			NumeroDeTemporadas INTEGER,
//			CapitulosTotales INTEGER,
//            PRIMARY KEY (IDAudiovisual)
//			);

	
	public static final String TABLA_CREADA="Tabla ContenidoAudiovisual creada correctamente.";
	public static final String TABLA_ERROR="Error al ejecutar la sentencia: ";
	//Base de datos ejecucion sentencias
	public static final String SENTENCIA_CREADA="Sentencia ejecutada correctamente.";
	public static final String SENTENCIA_ERROR="Error al ejecutar la sentencia: ";


	//Base de datos tipo sentencias
	public static final String SENTENCIA_SELECT_ID="SELECT IDAudiovisual FROM contenidoAudiovisual WHERE titulo = '";
	public static final String SENTENCIA_INSERT="INSERT INTO ContenidoAudiovisual(Titulo, Genero, ValoracionMedia, Fecha, Duracion, Director, Actores, NumeroDeTemporadas, CapitulosTotales) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
	public static final String SENTENCIA_UPDATE="UPDATE ContenidoAudiovisual SET ValoracionMedia = ? WHERE IDAudiovisual = ?";
	public static final String SENTENCIA_DELETE="DELETE FROM ContenidoAudiovisual where IdAudiovisual = ";
	public static final String SENTENCIA_BORRAR_TABLA="Drop table ContenidoAudiovisual";
	public static final String SENTENCIA_SELECT="SELECT * FROM ContenidoAudiovisual";
	public static final String SENTENCIA_SELECT_GENERO="SELECT * FROM contenidoAudiovisual WHERE genero=?";
	
}
