DROP TABLE PERSONA CASCADE CONSTRAINTS;
DROP TABLE ContenidoAudiovisual CASCADE CONSTRAINTS;

DROP TABLE FAVORITOS CASCADE CONSTRAINTS;
DROP TABLE HISTORIAL CASCADE CONSTRAINTS;

CREATE TABLE PERSONA (
    id_persona NUMBER PRIMARY KEY,
    nombre VARCHAR(100),
    contrasenia VARCHAR(100),
    tipo VARCHAR(1) CHECK (tipo IN ('A', 'U')),
    baneado NUMBER(1,0)
);

CREATE TABLE ContenidoAudiovisual (
			IDAudiovisual NUMBER GENERATED BY DEFAULT AS IDENTITY,
			Titulo VARCHAR(20),
			Genero VARCHAR(20),
			ValoracionMedia DECIMAL(4,2),
			Fecha DATE,
			Duracion NUMBER,
			Director VARCHAR(100),
			Actores VARCHAR(150),
			NumeroDeTemporadas INTEGER,
			CapitulosTotales INTEGER,
            PRIMARY KEY (IDAudiovisual)
			);

CREATE TABLE favoritos(
    IDFavorito NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_persona NUMBER,
    IDAudiovisual NUMBER,
    FOREIGN KEY (id_persona) REFERENCES PERSONA (id_persona),
    FOREIGN KEY (IDAudiovisual) REFERENCES ContenidoAudiovisual (IDAudiovisual)
);

CREATE TABLE historial(
    IDHISTORIAL NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_persona NUMBER,
    IDAudiovisual NUMBER,
    FOREIGN KEY (id_persona) REFERENCES PERSONA (ID_PERSONA),
    FOREIGN KEY (IDAUDIOVISUAL) REFERENCES CONTENIDOAUDIOVISUAL (IDAUDIOVISUAL)
);

INSERT INTO persona (id_persona, nombre, contrasenia,tipo,baneado) VALUES (1, 'Admin1', '1234','A',0);
INSERT INTO persona (id_persona, nombre, contrasenia,tipo,baneado) VALUES (2, 'Admin2', '5678','A',0);
INSERT INTO persona (id_persona, nombre, contrasenia,tipo,baneado) VALUES (3, 'Admin3', '4321','A',0);

INSERT INTO ContenidoAudiovisual (Titulo, Genero, ValoracionMedia, Fecha, Duracion, Director, Actores, NumeroDeTemporadas, CapitulosTotales)
VALUES ('Piratas del Caribe', 'Aventura', 4.5, TO_DATE('2003-07-09', 'YYYY-MM-DD'), 143, 'Gore Verbinski', 'Johnny Depp, Orlando Bloom, Keira Knightley', NULL, NULL);

INSERT INTO ContenidoAudiovisual (Titulo, Genero, ValoracionMedia, Fecha, Duracion, Director, Actores, NumeroDeTemporadas, CapitulosTotales)
VALUES ('Deadpool', 'Acción', 4.2, TO_DATE('2016-02-12', 'YYYY-MM-DD'), 108, 'Tim Miller', 'Ryan Reynolds, Morena Baccarin, Ed Skrein', NULL, NULL);


SELECT * FROM PERSONA;

SELECT * FROM FAVORITOS;

SELECT * FROM HISTORIAL;

SELECT * FROM ContenidoAudiovisual;

